<a href="https://colab.research.google.com/github/Muskiee-04/Deep-Learning-experiments/blob/main/01_COLAB_TensorFlow_2_0_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="The-Northcap-University-NCU-logo.png">


## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [ ]:
!pip install tensorflow-gpu==1.13.1

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.13.1 (from versions: 2.12.0)
ERROR: No matching distribution found for tensorflow-gpu==1.13.1


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'1.13.1'

### Variables and constants in TF 1.x

#### Variables

In [ ]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [ ]:
#Getting shape of the variable
variable.get_shape()

TensorShape([2, 2])

In [ ]:
#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 22],
       [12, 47]], dtype=int32)>

In [ ]:
#If a session is not initialized we cannot access values in the Variable/Tensor
variable.numpy()

array([[30, 20],
       [10, 45]], dtype=int32)

In [ ]:
#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[30, 20]], dtype=int32)>

#### Getting values from variables

In [ ]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

#Getting shape of the variable
variable.get_shape()

#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

#If a session is not initialized we cannot access values in the Variable/Tensor
variable.numpy()


#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

#Getting values from variables
# Initialize variables for the session in TensorFlow 2.x
# tf.compat.v1.global_variables_initializer()

#Run the eval method on the evironment with provided session to retrive values from it
variable.numpy()

#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

#Getting values from constants
#Fatching the tensor from the tensor graph/session
tensor_value = tensor.numpy()

tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

In [ ]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

#Getting shape of the variable
variable.get_shape()

#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

# Accessing values in the Variable/Tensor using .numpy() in TensorFlow 2.x
variable.numpy()

#Able to slice a variable, and retrieve values from it
variable[:1].numpy()


#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

#Getting values from constants
#Fatching the tensor from the tensor graph/session
tensor_value = tensor.numpy()

tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

In [ ]:
# Access the value of the variable directly using .numpy()
variable_value = variable.numpy()

# Print the value
print(variable_value)

[[30 20]
 [10 45]]


#### Constants/Tensors

In [ ]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [ ]:
#We are still not able to get the real value without defining a session
# Instead of using tensor.eval(), use tensor.numpy() to get the values
tensor_value = tensor.numpy()

# Print the value
print(tensor_value)

[[23  4]
 [32 51]]


#### Getting values from constants

In [ ]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

# Instead of using tf.Session() and session.run(), use tensor.numpy() to get the values
tensor_value = tensor.numpy()

# Print the value
print(tensor_value)

[[23  4]
 [32 51]]


In [ ]:
# Instead of using session, directly initialize the global variables using tf.compat.v1
tf.compat.v1.global_variables_initializer()

In [ ]:
#Fatching the tensor from the tensor graph/session
# Instead of using session, directly use tensor.numpy() to fetch the values of the tensor
tensor_value = tensor.numpy()

#Print the values of the tensor
print(tensor_value)

[[23  4]
 [32 51]]


In [ ]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [ ]:
!pip install tensorflow==2.2.0

ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.0.post1, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0, 2.19.0rc0)
ERROR: No matching distribution found for tensorflow==2.2.0


In [ ]:
%tensorflow_version 2.2.0

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

'2.18.0'

### Constants/Tensors

In [ ]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [ ]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

### Getting values from constants

In [ ]:
#Getting values straight from a TensorFlow constant to numpy - withut sesion
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [ ]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [ ]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [ ]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [ ]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between scalar and tensor

In [ ]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between scalar and tensor

In [ ]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [ ]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [ ]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Operations with variables

In [ ]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting raw value from the variable

In [ ]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing specific value in the TensorFlow variable

In [ ]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Strings in TensorFlow 2.0

In [ ]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [ ]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
#How to iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Handling Devices in TensorFlow 2.0

#### CPU

In [ ]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

#### GPU

In [ ]:
if tf.config.list_physical_devices('CPU'):
  tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
  print(tf_string_array.device)
  print(tf_string_array)

/job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([b'TensorFlow' b'Deep Learning' b'AI'], shape=(3,), dtype=string)


In [ ]:
if tf.config.list_physical_devices('GPU'):

  tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

  print(tf_string_array.device)